require("lsp.servers.bash")
require("lsp.servers.css")
require("lsp.servers.dockerls")
require("lsp.servers.gopls")
require("lsp.servers.html")
require("lsp.servers.json")
require("lsp.servers.lua")
require("lsp.servers.pyright")
-- require("lsp.servers.r_language_server")
require("lsp.servers.rust_analyzer")
-- require("lsp.servers.typescript")
require("lsp.servers.vim")
require("lsp.servers.yaml")
require("lsp.servers.groovy")
require("lsp.servers.php")
require("lsp.servers.yaml")
-- require("lsp.servers.eslint")
-- require("lsp.servers.dcmls")
